/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface NdsFilterableList {}
  interface NdsTabInterface {}
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLNdsFilterableListElement extends Components.NdsFilterableList, HTMLStencilElement {}
  var HTMLNdsFilterableListElement: {
    prototype: HTMLNdsFilterableListElement;
    new (): HTMLNdsFilterableListElement;
  };

  interface HTMLNdsTabInterfaceElement extends Components.NdsTabInterface, HTMLStencilElement {}
  var HTMLNdsTabInterfaceElement: {
    prototype: HTMLNdsTabInterfaceElement;
    new (): HTMLNdsTabInterfaceElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'nds-filterable-list': HTMLNdsFilterableListElement;
    'nds-tab-interface': HTMLNdsTabInterfaceElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface NdsFilterableList extends JSXBase.HTMLAttributes<HTMLNdsFilterableListElement> {}
  interface NdsTabInterface extends JSXBase.HTMLAttributes<HTMLNdsTabInterfaceElement> {}

  interface IntrinsicElements {
    'my-component': MyComponent;
    'nds-filterable-list': NdsFilterableList;
    'nds-tab-interface': NdsTabInterface;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


